import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#dce5d9',
        'on-secondary-container': '#afb8ad',
        'inverse-on-surface': '#3e2c2b',
        'on-background': '#f9dcda',
        'on-tertiary-container': '#00302c',
        'on-error-container': '#ffdad6',
        surface: '#1e0f0f',
        'on-surface': '#f9dcda',
        'secondary-container': '#404940',
        'on-primary-container': '#5b000e',
        'on-error': '#690005',
        'error-container': '#93000a',
        error: '#ffb4ab',
        secondary: '#c0c9be',
        tertiary: '#6fd8cc',
        'inverse-primary': '#bb152c',
        'inverse-surface': '#f9dcda',
        'surface-variant': '#433030',
        'on-tertiary-fixed': '#00201d',
        'on-primary-fixed': '#410007',
        'on-secondary-fixed': '#161d16',
        'on-tertiary': '#003733',
        'surface-bright': '#473534',
        'tertiary-fixed': '#8cf4e8',
        'on-primary-fixed-variant': '#92001c',
        'on-secondary': '#2a322b',
        'surface-dim': '#1e0f0f',
        'outline-variant': '#5b403f',
        'primary-fixed': '#ffdad8',
        'on-tertiary-fixed-variant': '#00504a',
        'surface-container-high': '#372625',
        'surface-container-highest': '#433030',
        background: '#1e0f0f',
        'surface-container-lowest': '#180a0a',
        'on-surface-variant': '#e4bebc',
        'surface-container': '#2c1b1b',
        primary: '#ffb3b1',
        'primary-container': '#ff535b',
        'primary-fixed-dim': '#ffb3b1',
        'on-primary': '#680011',
        'surface-tint': '#ffb3b1',
        'on-secondary-fixed-variant': '#404940',
        'surface-container-low': '#271717',
        'tertiary-container': '#2fa096',
        'secondary-fixed-dim': '#c0c9be',
        'tertiary-fixed-dim': '#6fd8cc',
        outline: '#ab8987',
        'brand-crimson': '#ab0511',
        'brand-offwhite': '#F1FAEE',
        'brand-black': '#0A0A0A',
        'brand-card': '#161616',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '120px',
        'margin-desktop': '64px',
        base: '8px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'body-md': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'display-xl': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'headline-h2': ['Space Grotesk', 'sans-serif'],
        'headline-h1': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '150%', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '100%', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-xl': ['120px', { lineHeight: '100%', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-xl-mobile': ['52px', { lineHeight: '100%', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg': ['80px', { lineHeight: '105%', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['38px', { lineHeight: '105%', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '160%', letterSpacing: '0em', fontWeight: '400' }],
        'headline-h2': ['32px', { lineHeight: '120%', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-h1': ['48px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
